# Generated by Django 6.0.1 on 2026-02-01 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_ug_client_txn_id_transaction_ug_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCustomer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Customer',
                'verbose_name_plural': 'Vendor Customers',
                'unique_together': {('user', 'phone')},
            },
        ),
    ]
