# Generated by Django 6.0.1 on 2026-01-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kyc_subscription_qrstandorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrstandorder',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
