# Generated by Django for Nepal Payment (OnePG) integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_ug_client_transaction_id_to_ug_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nepal_merchant_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
