# Generated by Django 6.0.1 on 2026-01-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('country_code', models.CharField(default='91', max_length=5)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='country_code',
            field=models.CharField(default='91', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='91', max_length=5),
        ),
    ]
