# Generated by Django 6.0.1 on 2026-01-30 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_otp_order_country_code_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersetting',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supersetting',
            name='due_threshold',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='supersetting',
            name='is_subscription_fee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supersetting',
            name='is_whatsapp_usage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supersetting',
            name='per_transaction_fee',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='supersetting',
            name='share_distribution_day',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='supersetting',
            name='ug_client_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supersetting',
            name='whatsapp_per_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='due_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_shareholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='share_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ug_client_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ShareholderWithdrawal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shareholder Withdrawal',
                'verbose_name_plural': 'Shareholder Withdrawals',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('utr', models.CharField(blank=True, max_length=100, null=True)),
                ('vpa', models.CharField(blank=True, max_length=100, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=10)),
                ('transaction_category', models.CharField(choices=[('order', 'Order Payment'), ('transaction_fee', 'Transaction Fee'), ('subscription_fee', 'Subscription Fee'), ('whatsapp_usage', 'WhatsApp Usage'), ('qr_stand_order', 'QR Stand Order'), ('share_distribution', 'Share Distribution'), ('share_withdrawal', 'Shareholder Withdrawal'), ('due_paid', 'Due Paid')], default='order', max_length=30)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.order')),
                ('qr_stand_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.qrstandorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
